### ISSUE TITLE
Add covered_strength for languages that don't provide it

### ISSUE THREAD

**Issue by GordonDiggs** [codeclimate/test-reporter#116]
The algorithm is here: http://www.rubydoc.info/github/colszowka/simplecov/SimpleCov%2FSourceFile:covered_strength

**Comment by ale7714** [comment]
I've tested on our JS repo and we have `covered_strength` for files as expected :). 

@GordonDiggs the concept `covered_strength` applies only for files? Currently we send `covered_strength` for the whole test report but it's always 0 because we would need to calculate that value if we wanted it. WDYT?

**Comment by GordonDiggs** [comment]
@ale7714 looks like we store it at the test report level, but don't use it anywhere. I'd leave it alone for now

**Comment by ale7714** [comment]
i'm closing this issue for now then :)
