### ISSUE TITLE
Questions on travis usage

### ISSUE THREAD

**Issue by VladShcherbin** [codeclimate/test-reporter#217]
Hey, I've seen an [example of travis](https://docs.codeclimate.com/docs/travis-ci-test-coverage) usage in the docs:

```
env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: ruby
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - bundle exec rspec
  # Preferably you will run test-reporter on branch update events. But 
  # if you setup travis to build PR updates only, you don't need to run 
  # the line below
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  # In the case where travis is setup to build PR updates only, 
  # uncomment the line below
  # - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
```

I've got some questions about it:

1) Why do we need to set `GIT_COMMITTED_AT` env variable?
2) In package readme, `before-build` is executed before tests. It's not executed in example, why?
3) In example, in the last step, after tests are executed,  there is `if [ "$TRAVIS_PULL_REQUEST" == "false" ];`. What is it used for?

**Comment by ale7714** [comment]
Hi @VladShcherbin  👋  , sorry for the late response.

I'm gonna start by replying the last question 

> 3. In example, in the last step, after tests are executed, there is if [ "$TRAVIS_PULL_REQUEST" == "false" ];. What is it used for?

TravisCI has the concept of branch builds and pull request builds. Users that use both will triggered 2 builds every time they open or change a PR. A Pull Request build runs on a detached `HEAD`. But we prefer to run the test reporter on branch builds because if the `test-reporter` needs to shell out to git, it would get accurate information. 

This would help me reply to your first question,

> 1. Why do we need to set GIT_COMMITTED_AT env variable?

It's not required and the `test-reporter` will get the value by shelling out to `git`. Even when we encourage users to run the test reporter on a branch build, an user may still run it on a pull request build. And that's why on the example we show how to the right `GIT_COMMITTED_AT` on either kind of build. 

> 2. In package readme, before-build is executed before tests. It's not executed in example, why?

Currently, `before-build` is no-op. But as we keep working on the tool we will be adding functionality and that way users won't have to update their setup to include `before-build`.

After thinking about this, I see there's room to simplify the example on our docs and add some clarifications around Pull Request builds. I will make a note to review that. Let me know if you have any other question.

**Comment by VladShcherbin** [comment]
@ale7714 thank you for the info, it'll be great to add this to the docs for other devs and maybe a simple example when you don't care about PR's, only commits.
