### ISSUE TITLE
[SOLVED] Support for Jacoco coverage in Java projects does not work.

### ISSUE THREAD

**Issue by mikebocian** [codeclimate/test-reporter#243]
I've got a Java project built by Gradle with Jacoco plugin as a coverage provider ( I am using Jacoco because it is supported almost out-of-the-box in Gradle ) 

I would like to use CodeClimate also as a coverage browser. But there is a few things which need to be fixed before anyone uses it with this stack.
At first I would like to format coverage by using your tool. I try to do that by test-reporter format-coverage --input-type jacoco

1) After build, the report by default is generated under <root>/build/report/jacoco/test/jacocoTestReport.xml. test_reporter by default is not looking for this name and there is no way to point the file in the test_reporter parameter. 
2) When the file, after renaming to jacoco.xml and moving to the root directory of the repository, test_reporter find it correctly. But it does not finding classes which are pointed in the .xml file. It says: 
ERRO[0000] failed to read file com/package/name/ClassName.java

I know that you probably support Cobertura, but for now it is not an option for me.

### Edit 11/09/2017:
If you're experiencing this issue take a look on @jisikoff's [workaround](https://github.com/codeclimate/test-reporter/issues/243#issuecomment-342799734).

**Comment by ale7714** [comment]
Hi @mikebocian, thank you for trying out our new test reporter. I'm sorry that you're finding some issues on the setup but I'm happy to help out. 
If you can give me some more specific details on how are you running your test and the `test_reporter` it would be really helpful.
But to start I can suggest replacing `after-build` command with the use of the low level commands (`format-coverage` and `upload-coverage`) so you can point to the coverage file. It would look something like: 
```
./cc-test-reporter format-coverage -d -t jacoco /build/report/jacoco/test/jacocoTestReport.xml
./cc-test-reporter upload-coverage -d 
```
Also, I included on the example above the flag `-d` this would return debug output that can help us troubleshoot other details.  
Let me know if you have any other question.

**Comment by mikebocian** [comment]
@ale7714 I've check your Issues on Github, and I've already tried a few things. The first thing was to use the mentioned low-level commands. This issue is the result of trying to run the `format-coverage`

**Comment by ale7714** [comment]
@mikebocian I see. Please, can you share with me the commands you're using? and also the output from the `test-reporter` when you add the flag `-d` to the commands?

**Comment by ale7714** [comment]
@mikebocian thanks for sharing those details. Let's see if I understand correctly, your project directory looks something like 
```
app_source/ 
    src/
        main/
            java/
                /com 
                   /package 
                       ... # java files 
```

And the `test_reporter` is not aware of  `src/main/java`. If this information on the jacoco.xml report? It looks like the test reporter is failing to parse information on the report that would correctly to the location of the files. Can you share your xml with us? If you don't feel comfortable sharing that here, you can also do it on our support channel at http://www.codeclimate.com/help? 

Again, sorry for the hiccups. Hopefully we'll sort this out soon :).

**Comment by mikebocian** [comment]
As far as I can see, jacoco.xml does not have an information about the structure of the project sources. It only knows the name of the class. I thing the solution to the problem would be to introduce two parameters to format-coverage command.
1) Path to the jacoco xml test result
2) Path to the roots of the source.

If it necessary, I will send the files to your support channel.

**Comment by ale7714** [comment]
@mikebocian it would be really helpful to have the Jacoco report. Once I have it, I'll discuss this issue internally and also your proposed solution. I'll update this issue as soon as I have an update. Thank you for your patience.

**Comment by ale7714** [comment]
@mikebocian thanks for sharing the xml with us. I've been reading a bit more about the jacoco setup and it looks like it's possible to setup the source directory as the root of the project. What do you think about trying that? What's your current JaCoCo setup?

**Comment by jisikoff** [comment]
Any word on this? I have the same problem.

**Comment by ale7714** [comment]
@jisikoff 👋, can you let me know more details on the issue you are having?

**Comment by jisikoff** [comment]
It appears perhaps this line of code https://github.com/codeclimate/test-reporter/blob/6071de5269610044f03611a5a9200cdce9b579ac/formatters/source_file.go#L92 should be after the --add-prefix is applied in this file so that the gitblob function uses the add-prefixed name to find the source files.   My project structure looks like:

app_source/ 
  webapp/
    src/
        main/
            java/
                /com 
                   /package 
                       ... # java files 
and my jacoco reports go to  webapp/build/reports/jacoco/test/jacocoTestReport.xml 
    
if I run: ./cc-test-reporter format-coverage -t jacoco --add-prefix webapp/src/main/java/ -d webapp/build/reports/jacoco/test/jacocoTestReport.xml 

I get the same error as the user above in the blobid can't be retrieved because the prefix is not applied before trying to retrieve it in that line of code Notice the prefix is not applied in the path being searched for in the error:

DEBU[0000] coverage path webapp/build/reports/jacoco/test/jacocoTestReport.xml 
DEBU[0000] using formatter jacoco                       
DEBU[0000] checking search path webapp/build/reports/jacoco/test/jacocoTestReport.xml for jacoco formatter 
DEBU[0000] couldn't load branch from ENV, trying git... 
DEBU[0000] couldn't load commit sha from ENV, trying git... 
DEBU[0000] couldn't load committed at from ENV, trying git... 
INFO[0000] triming with prefix /Users/jeremy/code/auth/
 
DEBU[0000] getting fallback blob_id for source file com/cinchfinancial/auth/message/migration/V20170901112900__send_verified_users.java 
**ERRO[0000] failed to read file com/cinchfinancial/auth/message/migration/V20170901112900__send_verified_users.java
open com/cinchfinancial/auth/message/migration/V20170901112900__send_verified_users.java: no such file or directory 
Error: open com/cinchfinancial/auth/message/migration/V20170901112900__send_verified_users.java: no such file or directory**

**Comment by ale7714** [comment]
@jisikoff sorry for the late response. 
I see what you mean although the original intent of `--add-prefix ` was to allow user to add a prefix when they run tests on an environment that doesn't match their git structure but that way they can update file paths to match. 
How is jacoco setup to load the files? is it possible to configure the root directory and load files from the source? 

A workaround comes to mind,  you could run the `test-reporter` from `webapp/src/main/java/`. Something like:
```
# after running java tests
cd webapp/src/main/java/ 
../../../.././cc-test-reporter format-coverage -t jacoco  --add-prefix webapp/src/main/java/ ../../../build/reports/jacoco/test/jacocoTestReport.xml
cd  # cd back to project root 
./cc-test-reporter upload-coverage --input webapp/src/main/java/coverage/codeclimate.json
```

what do you think about trying this?

**Comment by jisikoff** [comment]
I originally did something like that which does work but looks ugly so I ended up just writing a gradle task that fixes the paths inside the jacoco test report and copying it  before running the test reporter.  It would be nicer if this wasn't necessary though:
```  
task jacocoFix(type: Copy) {
        from 'build/reports/jacoco/test/jacocoTestReport.xml'
        into '../'
        rename { String fileName ->
            fileName.replace("jacocoTestReport.xml", "jacoco.xml")
        }
        filter { line -> line.replaceAll("com/", "webapp/src/main/java/com/") }
    }
```

**Comment by ale7714** [comment]
@jisikoff thanks for sharing this workaround 👏 . I looks way better. I'll keep this issue open to have the feedback and discuss it internally. 

@mikebocian what do you think about trying this workaround?

**Comment by mikebocian** [comment]
It's not the perfect one, but it works. The problem is when you have two separate directories with source. Like: `src/main/java` and `generated/main/java`. You have to manually exclude all `generated` ones from Jacoco, using something like:

```
jacocoTestReport {
    reports {
        xml.enabled true
    }

    afterEvaluate {
        classDirectories = files(classDirectories.files.collect {
            fileTree(
                    dir: it,
                    exclude: [
                            '**/package/internalrpc/**',
                            '**/package/other/**',
                            '**/SomeGrpc*.class',
                            '**/SomeOuterClass*.class'
                    ]
            )
        })
    }
}
```

Hope it will help someone. 

But ok, for me it is not an issue anymore. Workaround is working quite ok.

**Comment by lawonga** [comment]
What do you do if you're trying to `format-coverage` on a merged jacoco report built from many different jacoco reports?

Manually go through the report and populate the prefix/directories?

**Comment by wfleming** [comment]
If you have many different jacoco reports derived from source trees in different working directories, you would need to pass appropriate flags to `format-coverage` for each specific report before merging them with `sum-coverage`. Please see our [docs on parallel/multiple test suites](https://docs.codeclimate.com/docs/configuring-test-coverage#section-parallel-and-multiple-test-suites) for more details on the different steps involved in handling multiple test reports.

Ultimately what the Code Climate API is expecting is to receive a single report with file paths that are relative to the root of the git repository, since reports need to be for a single git repository. Stripping and adding prefixes on each individual report is the operation performed to ensure paths from the individual reports get changed to be relative to the root of the git repository so that a final, combined report can be assembled with correct file paths.

**Comment by toymachiner62** [comment]
Is this going to get fixed or are we going to have to continue to use the hacky workaround?

**Comment by toymachiner62** [comment]
@jisikoff being a complete n00b to gradle, do I need to do anything to call this task in my gradle build?

> task jacocoFix(type: Copy) { from 'build/reports/jacoco/test/jacocoTestReport.xml' into '../' rename { String fileName -> fileName.replace("jacocoTestReport.xml", "jacoco.xml") } filter { line -> line.replaceAll("com/", "webapp/src/main/java/com/") } }

**Comment by jisikoff** [comment]
you call it like any other gradle task, the task name is "jacocoFix" so an example gradle command might be something like:

```
gradle clean build jacocoTestReport jacocoFix
```

**Comment by ale7714** [comment]
👋 all,

Wanted to post a quick update to let everyone know that the `test-reporter` was updated a couple of months ago. Making it possible to setup the `test-reporter` without the manual workaround. 

Instead of after-build, please use these two sub-commands_

1. `format-coverage`, which has 2 important settings:

      [`JACOCO_SOURCE_PATH`](https://github.com/codeclimate/test-reporter/blob/master/man/cc-test-reporter-format-coverage.1.md#environment-variables): the path to Java source files
        coverage file: to path to JaCoCo coverage XML file

1. upload-coverage

Example:
```
JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter \
  format-coverage target/site/jacoco/jacoco.xml     \
  --input-type jacoco
./cc-test-reporter upload-coverage
```

Thank you for your feedback all!
