### ISSUE TITLE
Coverage Reports are uploading successfully but no coverage in code climate UI.

### ISSUE THREAD

**Issue by wahab054** [codeclimate/test-reporter#273]
Hi Code Climate Team, 
I've been using your cc-test-reporter as your documentation suggested with CodeshipCI. I have a set of parallel tests running in different containers/services. I'm using the low level commands.
`format-coverage` after every test batch then upload to S3.
after testing finishes, I download all reports, and then `sum-coverage` to create a combined report.
Next, `upload-coverage` to send it to S3. this step returns a success message.
But the code climate dashboard shows no badge for Test Coverage. When I checked with the Badge API: `https://api.codeclimate.com/v1/badges/cfd7bad4e14ddcc3e8bb/test_coverage` it returned **Test Coverage ?**

I even checked with your REST API `https://api.codeclimate.com/v1/repos/:repo_id/test_reports` all my uploaded reports were returned.

**Comment by wfleming** [comment]
Hi @wahab054,

Sorry for the trouble.

Would you mind sharing the exact `test-reporter` commands you're running for each of the subcommands, including any flags and arguments you're passing?

On our backend I can see some validation errors processing the coverage reports due to invalid file paths in the report: the paths start with `/` and look like absolute paths. If you're using `--prefix`with `format-coverage` right now you might need to adjust the value there?

I can share the file paths here if you like, but of course don't want to do that without your permission since some people consider filepaths sensitive information. You can also get in touch with our support team at https://codeclimate.com/help where it's easier to discuss sensitive aspects of people's repositories instead of a public GitHub issue.

**Comment by wahab054** [comment]
Thank you, so much for your support. Yes, the issue was with a few paths, now fixed.
