### ISSUE TITLE
Test Coverage missing after running cc-test-reporter after-build

### ISSUE THREAD

**Issue by sadok-f** [codeclimate/test-reporter#352]
Hi there!

I have a Test Coverage issue for my open source repo, if you check here https://codeclimate.com/github/flyimg/flyimg
the Test Coverage is empty and not shows any numbers, this is strange since I already pushed the test coverage generated via the new tools `./cc-test-reporter after-build` you can check the command here https://github.com/flyimg/flyimg/blob/master/.travis.yml

Here the last build output which says `Test report uploaded successfully to Code Climate`
https://travis-ci.org/flyimg/flyimg/builds/412668804#L629

Attached I put a screenshot for Trends Test Coverage which shows that it's uploaded but somehow it displayed in the repo overview.
https://codeclimate.com/github/flyimg/flyimg/trends/test_coverage_total

Thank you in advance!

**Comment by viralanomaly** [comment]
I'm experiencing this as well.  I can see the results of my test coverage in the Test Report, but the badge on the front page of the repo in code climate as well as in github remain blank/question mark.

**Comment by wfleming** [comment]
Hi,

We very recently added more details on uploaded test reports to the Test coverage page within your Repo settings. If you navigate to the page mentioned at https://docs.codeclimate.com/docs/finding-your-test-coverage-token, you'll find a list of recently uploaded reports, along with error details for cases where the report was determined to be invalid. There is processing done to the to the test coverage results after the initial upload that does further validations, which is why you'd see a `Test report uploaded successfully to Code Climate`, but the test report would later be determined to be invalid.

@sadok-f In the case of `flyiomg/flyimg` I can see two things that are probably problematic:

- Your test coverage file seems to be referencing files by an absolute path, and our backend requires files to be relative to the repository root. I suspect this is related to your running your tests in a built docker container & probably some side effects of how your coverage is collected within that container. I see you're using the `-p` tag on the test reporter, but I don't think the value you have right now is the correct one. I think you want to strip `/var/www/html/`
- Many of your recent test reports are being sent with their branch as `HEAD`, which isn't correct and is going to prevent from master branch coverage reports being counted towards the trend report. This is probably also related to the docker container: on Travis, we collect git information from env vars that Travis sets, like `GIT_BRANCH`, but when running the test reporter in a docker container the reporter can't see that ENV anymore and may not be collecting correct values.

  You could forward the appropriate env into the container when you `docker exec`: you'd want to forward every env var starting with `TRAVIS_` listed in the constants in [this file](https://github.com/codeclimate/test-reporter/blob/871a40f133fea977ed119a6af5e7766c61f82a32/env/git.go).

  However, in your case I think it might be simpler to actually install and execute the `cc-test-reporter` outside of the docker container. Because you have `PWD` mounted into the running docker container, I think you could just install & run the test reporter outside of the docker container and it should work.

@viralanomaly you didn't mention what repo you're experiencing this issue with, so I can't give more specific feedback here, but if you check out the the recent test reports for your repository I suspect you'll find that they're invalid for one reason or another.

Hope that's helpful, let me know if you have further questions.

**Comment by viralanomaly** [comment]
I expect mine to have similar problems to what you were just discussing.  I'm brand new to all of this.  My repo is private - if I give you the link to it in codeclimate, is that sufficient for you to identify it and see what is going on?

**Comment by viralanomaly** [comment]
Or I forgot to actually trigger the build on my default branch, so there was nothing reported from it... I was the problem. :)

**Comment by wfleming** [comment]
@viralanomaly you should probably contact our support via https://codeclimate.com/help/new

**Comment by wfleming** [comment]
Oh, heh, well, if that was all that was causing an issue in your case, then I'm glad that was an easy fix @viralanomaly :wink:. If you do have further problems though, I would suggest filing a ticket with our support team.

**Comment by sadok-f** [comment]
Thank you @wfleming for your response, I updated my script to replace the absolute path with relative one and I moved the `cc-test-reporter` outside de docker and everything works perfectly and I got back the Test coverage badge.

Thank you again!
